
server:
  port: 8082
spring:
  kafka:
    topic: library-events
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group