
server:
  port: 8082
spring:
  kafka:
    topic: library-events
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group

  datasource:
    url: jdbc:mysql://172.17.0.1:3306/library?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          ddl-auto: update
          show-sql: true